[git] Additional cleaning in githooks

diff --git a/.git_template/hooks/clang-format b/.git_template/hooks/clang-format
--- a/.git_template/hooks/clang-format
+++ b/.git_template/hooks/clang-format
@@ -3,7 +3,10 @@
 # Runs clang-format on changed regions before commit.
 #
 
-git stash save -k "clang_format_stash"
-git clang-format
-git add -p
-git stash pop
+readonly out=$(git clang-format -v --diff)
+
+if [[ "$out" == *"no modified files to format"* ]]; then exit 0; fi
+if [[ "$out" == *"clang-format did not modify any files"* ]]; then exit 0; fi
+
+echo "ERROR: you need to run git clang-format on your commit"
+exit 1
